version: 2.1 #versi dari konfigurasi CircleCI yang digunakan.
jobs: #berisi definisi dari setiap job yang akan dijalankan dalam pipeline.
  build-and-push-karsajobs: #nama job
    docker: #mementukan image yang akan digunakan dalam job ini
      - image: docker:stable #image docker
    steps: #langkah yang akan dijalankan dalam job
      - checkout #melakukan checkout repository.
      - run: #menjalankan perintah yang ada dibawah
          name: Lint Dockerfile #nama langkah
          #perintah yang akan dijalankan
          command: |
            apk add --no-cache curl
            curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-$(uname -s)-$(uname -m)"
            chmod +x /usr/local/bin/hadolint
            hadolint Dockerfile
      - run: #menjalankan perintah yang ada dibawah
          name: Test App #nama langkah
          #perintah yang akan dijalankan
          command: |
            apk add --update go
            go version
            go test -v -short --count=1 $(go list ./...)
      - setup_remote_docker: #add docker remote
          version: 20.10.14 #version docker
          docker_layer_caching: true #layer caching
      - run: #menjalankan perintah yang ada dibawah
          name: Build and Push Image #nama langkah
          #perintah yang akan dijalankan
          command: |
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest docker.pkg.github.com/adityaayatusy/a433-microservices/karsajobs:latest
            echo ${PERSONAL_ACCESS_TOKEN} | docker login docker.pkg.github.com -u adityaayatusy --password-stdin
            docker push docker.pkg.github.com/adityaayatusy/a433-microservices/karsajobs:latest

workflows: #mendefinisikan alur kerja dari pipeline.
  version: 2 #versi dari definisi workflows.
  karsajobs: #nama workflows
    jobs: #menentukan urutan job-job yang akan dijalankan dalam workflows.
      - build-and-push-karsajobs:
          context: GITHUB #context environment
